# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        path: ./cl-string-generator
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        ros install lem
        ls
        ros install cxxxr/sblint
        export PATH=$HOME/.roswell/bin:$PATH
        lem-test
        sblint lib/base/lem-base.asd
        sblint lib/core/lem-core.asd
