name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        set -ex

        ros config set dynamic-space-size 2048
        curl -L https://qlot.tech/installer | bash
        export PATH="/home/runner/.qlot/bin:$PATH"

        qlot install

        qlot exec .qlot/bin/sblint src/base/lem-base.asd
        qlot exec .qlot/bin/sblint lem.asd
        qlot exec .qlot/bin/sblint lib/lisp-syntax/lem-lisp-syntax.asd
        qlot exec .qlot/bin/sblint extensions/lisp-mode/lem-lisp-mode.asd

        if [ $(grep -r --include="*.lisp" 'lem::' | wc -l) -ne 0 ]; then
          echo 'using `lem::` internal symbols'
          echo 'https://google.github.io/styleguide/lispguide.xml?showone=Packages#Packages'
          exit 1
        fi

        qlot exec .qlot/bin/rove lem-tests.asd
        qlot exec .qlot/bin/rove extensions/vi-mode/lem-vi-mode.asd
